# Generated by Django 5.1 on 2024-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_prd_type_rename_price_product_sales_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Rice', 'Rice'), ('Grains', 'Grains'), ('Meat', 'Meat'), ('Dairy', 'Dairy'), ('Beverages', 'Beverages'), ('Pantry', 'Pantry'), ('Spices', 'Spices'), ('Oils', 'Oils'), ('Juice', 'Juice'), ('Canned', 'Canned'), ('Bread', 'Bread'), ('Pasta', 'Pasta'), ('Snacks', 'Snacks'), ('Bakery', 'Bakery'), ('Cereals', 'Cereals'), ('Condiments', 'Condiments'), ('Miscellaneous', 'Miscellaneous'), ('Chips', 'Chips'), ('Cookies', 'Cookies'), ('Candy', 'Candy'), ('Ice Cream', 'Ice Cream'), ('Frozen Foods', 'Frozen Foods'), ('Powders', 'Powders'), ('Herbs', 'Herbs'), ('Tea', 'Tea'), ('Coffee', 'Coffee'), ('Baking Supplies', 'Baking Supplies'), ('Books', 'Books'), ('Canned Goods', 'Canned Goods'), ('Bottled Goods', 'Bottled Goods')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='prd_type',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('Pack', 'Pack'), ('Box', 'Box'), ('KG', 'KG'), ('Signle', 'Signle')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('Pack', 'Pack'), ('Box', 'Box'), ('KG', 'KG'), ('Signle', 'Signle')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='prd_type',
        ),
    ]
