# Generated by Django 5.1 on 2024-09-01 09:02

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ptransaction_stransaction_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, null=True, region=None, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
