# Generated by Django 5.1.1 on 2024-09-06 05:46

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91 ', max_length=15, null=True, region='IN', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+91 ', max_length=15, null=True, region='IN', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
