# Generated by Django 5.1.1 on 2024-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_customer_balance_alter_supplier_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stransaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
