# Generated by Django 5.1.1 on 2024-10-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_subcategory_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_product.png', upload_to='product_images/')),
                ('name', models.CharField(max_length=255)),
                ('print_name', models.CharField(blank=True, max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('purchase_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('purchase_type', models.CharField(choices=[('box', 'Box'), ('number', 'Number'), ('litre', 'Litre'), ('pack', 'Pack'), ('kg', 'Kilogram'), ('gram', 'Gram')], max_length=50)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('sales_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('sales_type', models.CharField(choices=[('box', 'Box'), ('number', 'Number'), ('litre', 'Litre'), ('pack', 'Pack'), ('kg', 'Kilogram'), ('gram', 'Gram')], max_length=50)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('tax', models.DecimalField(blank=True, choices=[(5.0, '5%'), (12.0, '12%'), (18.0, '18%'), (28.0, '28%')], decimal_places=2, default=0, max_digits=5)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=20)),
            ],
        ),
    ]
